CREATE TABLE IF NOT EXISTS ingredients(
        id BIGINT PRIMARY KEY AUTO_INCREMENT,
        name varchar(255) NOT NULL,
        price DOUBLE NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE ingredients ADD healthy BOOLEAN NOT NULL;